.github/workflows/test_and_deploy.yml, .gitignore, .pre-commit-config.yaml, LICENSE, MANIFEST.in, README.md, brainglobe_workflows/__init__.py, pyproject.toml, tests/test_unit/test_placeholder.py
decided to keep everything here instead of in `brainglobe-scripts` `brainglobe-scripts` is now obsolete.
this is a 1:1 copy of what @sfmig and I had done in `brainglobe-scripts/main`, with the package renamed to `brainglobe-workflows`
=> transfer back from `brainglobe-scripts`

asv.conf.json
Previously it was pointing to  "smg/cellfinder-cli-benchmark", but this has now been merged and the branch deleted
=> Update asv.conf.json to point to main branch

.github/workflows/test_and_deploy.yml, Dockerfile
As per discussion on Zulip, the Docker image distribution for `cellfinder` will be discontinued.
`workflows` is designed with a streamlined install, so long as users have a `conda` environment, they should be able to install the `cellfinder` workflow without any issues in a lightweight manner anyway.
=> Remove Docker build

README.md
We don't really document our intentions for this repo anywhere AFAIK (I may have missed something).
Details what this repo is for to developers, to guide our development efforts.
Kind of a part of https://github.com/brainglobe/brainglobe.github.io/issues/8 - linking here to remember to move to website, or crosslink.
N/A
No
It is an update to the docs.
- [n/a] The code has been tested locally
- [n/a] Tests have been added to cover all new functionality (unit & integration)
- [n/a] The documentation has been updated to reflect any changes
=> Clarify repo purposes

brainglobe_workflows/brainmapper/analyse/analyse.py
Deals with the rare case in which a detected cell falls outside of the area in space for which a raw data to atlas space transform exists. This likely happens due to incorrect classification of an artefact outside the brain, or poor quality registration. 
Adds a try/except to skip these cells, and also reports them to the log. 
Closes #42
This has been tested locally by running brainmapper and manually adding some cell candidates with coordinates far outside the brain. There are no automated tests added because there are no tests yet for any of this type of code, and it's out of scope for this PR. I've raised https://github.com/brainglobe/brainglobe-workflows/issues/70 to track this. 
No
No
=> Deal with cells falling outside of the registered atlas boundary

brainglobe_workflows/brainmapper/main.py, brainglobe_workflows/brainmapper/tools/parser.py, brainglobe_workflows/brainmapper/tools/prep.py
Before release, this will need `brainglobe-napari-io` to be updated to detect the renamed `brainmapper.json`.
Closes #63 
As it turns out the log file is named automatically, so this just changes the metadata file.
=> Rename incorrect instances of cellfinder to brainmapper

pyproject.toml
See https://github.com/brainglobe/BrainGlobe/issues/33 | This should be the final task in the list, so it actually closes https://github.com/brainglobe/BrainGlobe/issues/33 :scream: 
As per the version 1 release plan, this repository should depend on the meta-package rather than the individual tooling packages themselves.
As such, have added `brainglobe>=1.0.0` to the top of the dependency list.
Have left in the explicit `brainreg>=1.0.0` and `cellfinder>=1.0.0` dependencies, even though these (or the most recent versions) should be fetched by the meta-package anyway.
This just ensures that the minimum version of the meta-package that will be fetched must be one that adheres to our BrainGlobe version 1 update: IE fetching the new cellfinder package and brainreg plugins.
Depends on:
- …
=> Add hard dependency on brainglobe-meta package

brainglobe_workflows/brainmapper/main.py
Update references to brainglobe_space in brainmapper after name change.
=> brainglobe_space name change

brainglobe_workflows/brainmapper/parser.py
`source_custom_config_cellfinder` was changed to `user_specific_configuration_path` in https://github.com/brainglobe/cellfinder/pull/394, so we need to update the usage her as well.
Updates the usage.
[Please reference any existing issues/PRs that relate to this PR.](https://github.com/brainglobe/cellfinder/pull/394)
Made the changes locally so that tests worked.
No
No
=> Replace source_custom_config_cellfinder with newer function

brainglobe_workflows/cellfinder_core/cellfinder_core.py, pyproject.toml, tests/cellfinder_core/test_integration/test_cellfinder.py
We expect that the main way the workflows will be useful for users is as reference scripts that they can "copy-paste" and adapt to their workflows. Therefore for simplicity we agreed to remove the entry point for the cellfinder workflow script.
Related to #9 
Removes the entry point to the cellfinder workflow script
Please reference any existing issues/PRs that relate to this PR.
We had smoke tests for the entry point before but these are removed in this PR.
No
No
=> Remove entry point for cellfinder workflow

.github/workflows/test_and_deploy.yml
We are inspecting why CI is slow (work in progress) and this seemed a low hanging fruit which may improve a bit our timings.
It adds a step in the CI workflow for tests, for caching the cellfinder model. This is implemented in [`cellfinder` CI](https://github.com/brainglobe/cellfinder/blob/e6a887f1721b89d51328214b108e0da5401a24a9/.github/workflows/test_and_deploy.yml#L53C7-L58C59) but not here.
Related to #65. 
Please explain how any new code has been tested, and how you have ensured that no existing functionality has changed.
If this PR breaks any existing functionality, please explain how and why.
If any features have changed, or have been added. Please explain how the documentation has been updated (and link to …
=> Cache cellfinder model in CI

.github/workflows/test_and_deploy.yml
[CI on `macos-latest` (now a Silicon runner)](https://github.com/brainglobe/brainglobe-workflows/actions/runs/8848041813/job/24297125057#step:3:219) fails with `error: subprocess-exited-with-error` ~~when installing scikit-image,~~ when installing `pytables` ([presumably](https://stackoverflow.com/questions/73029883/could-not-find-hdf5-installation-for-pytables-on-m1-mac)) [because HDF5 libraries are missing.
](https://github.com/brainglobe/brainglobe-workflows/actions/runs/8848041813/job/24297125057#step:3:327)
* For the M1 CI, `brew install`s HDF5 libraries and adds them to the path.
* Ensures tests are run on Silicon and non-Silicon macs.
Partial solution to https://github.com/brainglobe/BrainGlobe/issues/63
This …
=> naive attempt at fixing HDF5

MANIFEST.in, README.md, asv.conf.json, benchmarks/cellfinder_core.py, pyproject.toml
We are exploring a systematic way to benchmark `brainglobe` workflows using [`asv`](https://asv.readthedocs.io/en/v0.6.1/). 
This PR fixes some issues running the  `cellfinder` workflow benchmarks (1) on a small GIN dataset and (2) on data available locally. 
This PR involves:
- edits on the asv config file (mainly to install in the asv environment the brainglobe-workflows package from the local repo),
- an update to the `setup_cache` function of the benchmarks,
- an option to run the benchmarks on locally available data using an environment variable, and
- edits to the readme file to reflect these updates.
1. Checkout this branch to get the latest version of the benchmarks locally.
1. Create a conda environment and …
=> Run cellfinder benchmarks on small data

benchmarks/benchmarks/cellfinder.py
We plan to run the benchmarks on a large dataset, so we need a larger timeout value.
Increases the timeout value for all benchmarks.
\
We will test it manually on the GA workflow of the internal runner.
\
\
=> Increase benchmarks timeout

brainglobe_workflows/brainmapper/main.py
Before submitting a pull request (PR), please read the [contributing guide](https://github.com/brainglobe/.github/blob/main/CONTRIBUTING.md).
Please fill out as much of this template as you can, but if you have any problems or questions, just leave a comment and we will help out :)
Cellfinder is now using PyTorch so functions related to suppressing TensorFlow error messages no longer exist.
Removes any comments and function calls relating to suppressing TensorFlow error messages.
Waiting on https://github.com/brainglobe/cellfinder/pull/418 to be merged
No
No
=> Remove calls to TensorFlow related cellfinder functions

.github/workflows/test_and_deploy.yml, benchmarks/asv.latest-github.conf.json, benchmarks/asv.pip.conf.json, pyproject.toml
I replaced the versions in the asv config too. Not 100% sure this is correct (@alessandrofelder?). 
Closes #41
=> Update supported Python versions and remove cibuildwheel config

pyproject.toml
Latest release of `brainglobe-workflows` is incompatible with latest `cellfinder`, because it tries to import `tensorflow`-related functionality. This is fixed in the development code by https://github.com/brainglobe/brainglobe-workflows/pull/112 but not released yet.
Makes sure the next release pins to a cellfinder version >= 1.3.0, so the API between the two packages in in-sync and up-to-date.
\
Not sure how to test this 😬 I have convinced myself I have thought this through.
No. It's an adaptation to the latest cellfinder release.
No
- [ \ ] The code has been tested locally
- [ \ ] Tests have been added to cover all new functionality (unit & integration)
- [ \ ] The documentation has been updated to reflect any …
=> pin to pytorch-version of cellfinder

pyproject.toml
It seems like we have redundant dependencies in `pyproject.toml` but would like to double check.
Remove dependencies that are included in brainglobe meta package.
Inspired by https://github.com/brainglobe/brainglobe-atlasapi/pull/310
Tests pass locally and on CI.
No.
No.
- [ n/a ] Tests have been added to cover all new functionality (unit & integration)
- [ n/a ] The documentation has been updated to reflect any changes
=> Slim dependencies

benchmarks/asv.latest-github.conf.json, benchmarks/asv.pip.conf.json
If we run the benchmarks using the current configurations on a local machine, we risk `pip` using its cache. This stops the benchmarks from being useful smoke tests for newer versions of dependencies breaking our code, which is a [key purpose of this repo](https://github.com/brainglobe/brainglobe-workflows/issues/57).
Stops `pip` from using cached dependencies when installing the package into the `asv` conda env.
\
Only understanding how pip works better. Suggestions for how to best test this welcome :thinking: 
No.
yes, but we should tackle that as a whole once we are happy with the workflows and our internal testing setup.
- [ \ ] The code has been tested locally
- [ \ ] Tests have been added to cover all new …
=> Avoid caching `pip` dependencies

.github/workflows/test_and_deploy.yml, tests/brainmapper/test_integration/test_registration.py
`imio` was still being used in the `brainmapper` tests. Replaced this with the appropriate `brainglobe-utils` function.
=> Replace `imio` with `brainglobe-utils`

pyproject.toml
Pin the version of brainglobe-utils to ensure that https://github.com/brainglobe/brainglobe-workflows/issues/137 is fixed when installing from pypi
=> Pin brainglobe-utils version

.github/workflows/test_and_deploy.yml
Seems using an OS specific cache, or refreshing the Windows cache has brought the Windows CI run times within the same range as the other OSes!
=> OS specific caches

.github/workflows/test_and_deploy.yml, pyproject.toml
Adds an extra run of the neuroinformatics/actions/test with napari installed from main. This action will only run during the weekly cron job.
=> Runs scheduled tests against napari main
